---
title: "Portfolio"
author: "Rachelle Balgit"
date: "`r Sys.Date()`"
output: html_document
---

# CV
Motivated student persuing degree in biomedical sciences, with a big interest in microbiology and data science. Excellent analytical and communication skills. Speaks fluent Dutch and English. Always eager to learn and seeking for new experiences.  I am always hard working, organized and capable of working in a team or individual. 

Education
Bachelor’s Degree
Life Sciences (biomedical sciences), Hogeschool Utrecht (2020-current)
•	Specializing in microbiology 
•	Minor in Data science for biology part 1 and 2 

Important Courses
•	Medical Microbiological Diagnosis 
•	Laboratory Tools 
•	Research in Microbiology
•	Immunology
•	Experimental Design  

Projects 
Project Genes & Proteins: Determination of expression of IL-8 with a green fluorescent protein 
•	Researching increased IL-8 protein levels of patients with an RSV infection

Project Microbiology: Determination of an infection associated with Neisseria gonorrhoeae of patients
•	Using PCR and VITEK 

Project Research Microbiology: Researching the outer membrane vesicles of Porphyromonas gingivalis of patients with parodontitis
•	Using spectrometry and different isolation methods 

Minor Data science for Biology 
• Data analysis using R 
  - RNA-sequencing 
  - Metagenomics 
  - Next Generation Sequencing 

Important Skills
•	MALDI-TOF
•	VITEK 
•	(Q)PCR 
•	ELISA 
•	Chromotography
•	Cultering of bacteria  

