---
author: "Rachelle Balgit"
date: "`r Sys.Date()`"
output: html_document
---

# MALDIquant 

Door mijn intresse in bacteriën en virussen heb ik in mijn derde jaar gekozen voor de specialisatie microbiologie. Hierbij moest ik voor een project werken met de bacterie _Porphyromonas gingivalis_. De bacterie werd hierbij blootgesteld aan verschillende concentraties magnesium en ijzer. Om het effect hiervan te meten op het aantal uitgescheiden outer membrane vesicles (OMV's), werd er gebruik gemaakt van een fluorescentie microscoop en MALDI-TOF MS. 

Voor MALDI-TOF MS data bestaat er een package genaamd MALDIquant, met een complete pipeline voor analyse. Omdat ik de MALDI-TOF MS een interessante techniek vind in de microbiologie, lijkt het me leuk om uit te zoeken hoe deze package werkt. 
Door op internet informatie te vinden over de package zou ik deze willen toepassen op mijn vorige project om de resultaten die ik toen had en nu heb te vergelijken. Hiermee zou ik in 4 dagen mee kunnen beginnen. 

De eerste twee dagen zal ik vooral oefenen met het gebruik van de package. Op internet zijn er verschillende manuals te vinden en die zou ik kunnen doorlopen met fake-data. Vervolgens kan ik proberen of ik de package kan laten runnen op mijn eigen data.  
