---
title: "The Future"
author: "Rachelle Balgit"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Door mijn intresse in de bacteriën en virussen heb ik in mijn derde jaar gekozen voor de specialisatie microbiologie. Hierbij moest ik voor een project werken met de bacterie Porphyromonas gingivalis. De data die ik verkreeg kwam uit een fluorescentie microscopie en massaspectrometrie (MS). Ik heb met veel plezier aan dit project gewerkt en zou daarom nu met de kennis die ik heb verkegen uit mijn minor Data Science for Biology deze data opnieuw willen analyseren. 

Voor de massaspectrometer data bestaat er een package genaamd MALDIquant, met een complete pipeline voor analyse. 
Graag zou ik hiermee werken omdat ik later denk ik wel vaker met de maldi ga werken. Ik zou graag stage willen lopen in een bedrijf wat ook onderzoek doet naar bacteriën die zorgen voor mondziektes. 

Door op internet informatie te vinden over de package zou ik deze willen toepassen op mijn vorige project om de resultaten die ik toen had en nu heb te vergelijken. Hiermee zou ik in 4 dagen mee kunnen beginnen. 
